### ISSUE TITLE
exhibition batch update: KeyError

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#143]
*reviewing [scrumdo story 121](https://www.scrumdo.com/projects/story_permalink/1098334)*

The problem seems to be that "Plone" is hard-coded in the script as the site root, but that is not how the actual site is configured.

```
plone@isaw4-dev:/srv/isaw.web$ bin/client1 run scripts/batch_update.py --dry-run /home/telliott/exhib-test-2.json 
2016-08-17 05:46:25 WARNING ZODB.blob (2914) Blob dir /srv/isaw.web/var/blobstorage/ has insecure mode setting
2016-08-17 05:46:29 WARNING plone.behavior Specifying 'for' in behavior 'Related items' if no 'factory' is given has no effect and is superfluous.
2016-08-17 05:46:29 WARNING plone.behavior Specifying 'for' in behavior 'Dynamic SearchableText indexer behavior' if no 'factory' is given has no effect and is superfluous.
2016-08-17 05:46:29 WARNING collective.quickupload.interfaces Importing interfaces from collective.quickupload.browser.interfaces is deprecated, please import from collective.quickupload.interfaces
2016-08-17 05:46:30 WARNING plone.behavior Specifying 'for' in behavior 'Enable Image Cropping' if no 'factory' is given has no effect and is superfluous.
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'canAddPressReleases'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'getContacts'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'canAddPressClips'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'getClips'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'canAddPressContacts'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'showTwoStatePrivateWarning'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'publishPressRoomInfrastructure'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.UpgradeFolders has a security declaration for nonexistent method 'getReleases'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.MyFormWrapper has a security declaration for nonexistent method 'RSS'
2016-08-17 05:46:33 WARNING Init Class Products.Five.metaclass.RedirectsView has a security declaration for nonexistent method 'errors'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "scripts/batch_update.py", line 67, in <module>
    site = getSite(app)
  File "scripts/batch_update.py", line 42, in getSite
    site = app.unrestrictedTraverse("Plone")
  File "/srv/isaw.web/eggs/Zope2-2.13.24-py2.7.egg/OFS/Traversable.py", line 285, in unrestrictedTraverse
    raise e
KeyError: 'Plone'
```

Here's the test file content:

```JSON
{
    "items": [
        {
            "/exhibitions/foobition/checklist": {
                "title": "Conical Sundial with Oscan Dedicatory Inscription",
                "context": "Stabian Baths, Pompeii",
                "date": "2nd century BCE",
                "dimensions": "H. 43 cm; W. 50.5 cm; D. 23 cm",
                "inventory_num": "2541",
                "lender": "Museo Archeologico Nazionale di Napoli",
                "medium": "Marble"
            }
        },
        {
            "/exhibitions/foobition/checklist": {
                "title": "Quadruple Vertical Sundial with Inscription",
                "context": "Little Metropolitan Church, Athens",
                "date": "ca. 300 CE",
                "dimensions": "H. 50.8 cm; W. 99 cm; D. 32 cm",
                "inventory_num": "1816,0610.186",
                "lender": "British Museum, London",
                "medium": "Marble",
                "notes": "Phaidros son of Zoilos, the archon who rebuilt the Theater of Dionysos at Athens c. 300 CE"
            }
        }
    ]
}
```

**Comment by cguardia** [comment]
Apologies for the lousy testing. Added a site argument for specifying the site, so "--site isaw" will work in this case. Tested it on staging.

**Comment by paregorios** [comment]
fixed!
