### ISSUE TITLE
scripts/batch_update.py is failing

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#434]
Urgent because we are trying to load content for an exhibition that opens 26 January. Was the Plone root path or name changed when we moved to the new server? 

As user "plone_buildout", execute:

```
bin/client1 run scripts/batch_update.py --dry-run /home/telliott/upload_test_20220121a.json 
```

and get the following traceback:

```
Traceback (most recent call last):
  File "/usr/local/plone-4.3/primary/parts/client1/bin/interpreter", line 345, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "scripts/batch_update.py", line 92, in <module>
    site = getSite(app)
  File "scripts/batch_update.py", line 64, in getSite
    site = app.unrestrictedTraverse(site_name)
  File "/usr/local/plone-4.3/primary/eggs/Zope2-2.13.30-py2.7.egg/OFS/Traversable.py", line 285, in unrestrictedTraverse
    raise e
KeyError: 'Plone'
```

**Comment by paregorios** [comment]
Script must be invoked with site value "isaw" thus:

```
bin/client1 run scripts/batch_update.py --dry-run --site=isaw /home/telliott/upload_test_20220121a.json
```

Thanks @alecpm
