### ISSUE TITLE
Migrate isaw.web  to Plone 5.1

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#481]

**Comment by sauzher** [comment]
I have this kind of erros on three Images that prevent some things going on (like access the object, or purge historystorage...) after migration

```
2024-12-18 06:32:35 ERROR ZODB.Connection Couldn't load state for plone.app.contenttypes.content.Image 0x352f26
Traceback (most recent call last):
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/Connection.py", line 800, in setstate
    self._reader.setGhostState(obj, p)
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 622, in setGhostState
    state = self.getState(pickle)
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 615, in getState
    return unpickler.load()
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 481, in _persistent_load
    return self.load_persistent(*reference)
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 523, in load_persistent
    self._cache.new_ghost(oid, obj)
TypeError: Cache values must be persistent objects.
2024-12-18 06:32:35 ERROR ZODB.Connection Couldn't load state for plone.app.contenttypes.content.Image 0x352f26
Traceback (most recent call last):
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/Connection.py", line 800, in setstate
    self._reader.setGhostState(obj, p)
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 622, in setGhostState
    state = self.getState(pickle)
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 615, in getState
    return unpickler.load()
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 481, in _persistent_load
    return self.load_persistent(*reference)
  File "/mnt/hdd3/projects/isaw4/isaw.web51/eggs/ZODB-5.3.0-py2.7.egg/ZODB/serialize.py", line 523, in load_persistent
    self._cache.new_ghost(oid, obj)
TypeError: Cache values must be persistent objects.
```

ERROR purging /isaw/about/pictureofaspeakeratISAW.jpeg (Image)
ERROR purging /isaw/graduate-studies/AinelGedida.JPG (Image)
ERROR purging /isaw/graduate-studies/ISAW_Foyer.tiff (Image)

the objects are also undeletable: `folder._delOb(id)` returns same traceback

@alecpm any suggestion about it?

**Comment by paregorios** [comment]
@sauzher all three of those images are very old content and are not being used in any pages or other contexts anywhere on the site. I have just successfully deleted all three of them through-the-plone on production.

**Comment by sauzher** [comment]
I deleted them on isaw-migration.jazkarta.com too. Thanks!
