### ISSUE TITLE
Migration 4.3.20 missing images on about > facilities > history

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#560]
Embedded images are missing on [the "History of the Buidling" page](https://isaw-migration.jazkarta.com/about/facilities/history) on the 4.3.20 migration instance. [Compare to production](https://isaw.nyu.edu/about/facilities/history).

**Comment by sauzher** [comment]
Traceback:

```
2024-12-03T10:59:28 ERROR root could not scale "<plone.namedfile.file.NamedBlobImage object at 0xe420670a2ad0>" of 'https://isaw-migration.jazkarta.com/about/facilities/copy_of_dwelling.gif'
Traceback (most recent call last):
  File "/usr/local/plone-5.1/migration/eggs/plone.namedfile-3.0.11-py2.7.egg/plone/namedfile/scaling.py", line 290, in create
    **parameters)
  File "/usr/local/plone-5.1/migration/eggs/plone.scale-1.4.2-py2.7.egg/plone/scale/scale.py", line 48, in scaleImage
    progressive=True)
  File "/usr/local/plone-5.1/migration/eggs/Pillow-6.2.2-py2.7-linux-aarch64.egg/PIL/Image.py", line 2084, in save
    save_handler(self, fp, filename)
  File "/usr/local/plone-5.1/migration/eggs/Pillow-6.2.2-py2.7-linux-aarch64.egg/PIL/JpegImagePlugin.py", line 621, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
IOError: cannot write mode RGBA as JPEG
```

**Comment by paregorios** [comment]
Embedded images are still missing on 5.x staging.

**Comment by paregorios** [comment]
Tom to check all images in this page for evil.
